### ISSUE TITLE
Feature request: Ignore also undefined props 

### ISSUE THREAD

**Issue by thebestgin** [brettz9/form-serialization#4]
Really cool lib.

What do you think, should undefined props also ignored like emty props?
In my case it would be a helpful feature.

Currently:
![image](https://user-images.githubusercontent.com/10037845/116694154-36501e00-a9bf-11eb-8bf8-fec5b42465b0.png)

**Comment by thebestgin** [comment]
Sorry, my undefined is a string.

**Comment by brettz9** [comment]
Btw, I haven't looked into it thoroughly, but the native [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) might replace the need for this library nowadays.

**Comment by thebestgin** [comment]
You are right. 
Thank you for your advice.
